spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: 'jdbc:h2:mem:taskservice_db'
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
executor-config:
  initialDelay: 0
  corePoolSize: 1
  delayBetweenRuns: 60
  awaitTermination: 60
